### ISSUE TITLE
Question: On Android: how to find out the ConnectWifi() response?

### ISSUE THREAD

**Issue by ogsadmin** [exendahal/maui_wifi_manager#2]
Hi,

I was playing with your nice WifiManager class and tried to automatically open a web page whenever a specific Wifi was connected (I am using Android). However, I cannot seem to get a useful response in the 

`
var status = await CrossWifiManager.Current.ConnectWifi(...);
`

call - it seems to always return an empty NetworkData object, regardless if connect was successful or not (e.g. wrong password).
I've digged a bit through the code and found that the task seems to complete, before the Android callback is called...

In WifiNetworkService,android.cs, in function ConnectWifi(), for my version of Android the RequestNetwork()-function is called - and this does not await any event, it just returns the (current/previous) _networkData member...

As I am only learning MAUI and Android, I wonder, if you could give me a hint on how to change the code to return a real (awaitable) Task object - or how to catch the _connectivityManager event from the client (user of the CrossWifiManager class) side...?

Thanks and best regards!

**Comment by exendahal** [comment]
Have you obtained the necessary permissions from the users and also added them to your Manifest file?

**Comment by ogsadmin** [comment]
Sure! I am able to list SSIDs and connect - everything seems to be working fine! I also see the _callback.NetworkAvailable (line 42 of WifiNetworkService.android.cs) being called (using the debugger running on a physical device).

However, the `_callback.NetworkAvailable` callback is called **after** (~1 second or so) the call `await CrossWifiManager.Current.ConnectWifi(...)` completes (I can see this in the debugger, too). The return value of the `status = await ConnectWifi(...)` function is empty, the parameter for the `_callback.NetworkAvailable` called a second later then has the correct data...

I suspect, that it is not really completing a task in `ConnectWifi(...)`, but that's currently too difficult for me to understand (working on it). I Would expect that the `ConnectWifi(...)` should return a "running" task object, which will be set to "completed" in the `_callback.NetworkAvailable` function - but there is no code in there. 

That's why I was asking for one of the follwoing:
- A hint on how to bubble up the  `_callback.NetworkAvailable` to my user code (e.g. provide an interface to registering a callback in the WifiManager class, which then can be called from `_callback.NetworkAvailable`)
- Understand why the Task object returned from `ConnectWifi(...)` immediately completes

Thanks!

**Comment by exendahal** [comment]
Added task to get network info after the connection is established with [this](https://github.com/exendahal/WifiManagerMAUI/commit/6ba1d7fa79743928fa9f74aea14457323d1e7ed0)

**Comment by ogsadmin** [comment]
Nice! After a quick test, this seems to work pretty well for Android R. I've tried to understand your change to add this for Android Q, too - but without success so far...

Any chance, you can take a look into this, too?

**Comment by exendahal** [comment]
Finding Android 10 devices here is quite challenging. Let me try to locate one and test the issue.

**Comment by ogsadmin** [comment]
Sorry, I did not want to bug - please don't put too much effort into this.
I am still trying to understand the mechanics of asyncronous/tasks, but maybe I should start with a simpler thing first.

**Comment by exendahal** [comment]
Add ConectWifi() response for Android 10 with the release. 1.0.4
