### ISSUE TITLE
msb3644 the reference assemblies for netcore v5.0 were not found

### ISSUE THREAD

**Issue by ik4iro** [exendahal/maui_wifi_manager#5]
Hello, i am using your maui_wifi_manager plugin with my vs2022 maui multi platform project.
During compilation I receive the error in question. What solution should I adopt?
Thank's
Vittorio

**Comment by exendahal** [comment]
Can you share the project dependencies from .sproj file?

**Comment by ik4iro** [comment]
[CIAO.zip](https://github.com/user-attachments/files/16577874/CIAO.zip)
[CIAO_sln.zip](https://github.com/user-attachments/files/16577875/CIAO_sln.zip)

![devenv_OOdUJF36FN](https://github.com/user-attachments/assets/b71aa7d5-b61e-4093-885f-2adf2e32a55e)
This is my project. This is the first time I write a maui application. 
I'm sorry if I bother you

**Comment by ik4iro** [comment]
I have the same error with your original "demo app".
I use vs2022 professional 17.10.5

**Comment by ik4iro** [comment]
![devenv_giU3FxoNAd](https://github.com/user-attachments/assets/320801dc-330a-4882-a10a-2a3c796c2f40)

your demoapp same error

**Comment by exendahal** [comment]
I successfully built your project on my machine and added the MAUI WiFi Manager package from the NuGet source. It seems there may be a workload issue on your machine. Here is the project running on my setup.
[CIAO.zip](https://github.com/user-attachments/files/16578295/CIAO.zip)

**Comment by ik4iro** [comment]
Now I try it. 
It's ok.
Thank you very much
