### ISSUE TITLE
AndroidRuntimeException

### ISSUE THREAD

**Issue by danygutmann** [exendahal/maui_wifi_manager#7]
Hey,
thank you for this great wifi helper! Scanning is working fine, at ConnectWifi and OpenWifiSetting i get this error message:

**Android.Util.AndroidRuntimeException:** 'Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?'

uf googeling is not solving the issue..
thanks Daniel

**Comment by exendahal** [comment]
Can you share your Device OS and Manufacturer?

**Comment by danygutmann** [comment]
Hey,
sorry, I could have done that right away when I created it...

Model: SM-S901B
Manufacturer: samsung
Name: Galaxy S22
OS Version: 14
Idiom: Phone
Platform: Android

**Comment by exendahal** [comment]
Hey @danygutmann did you manage to resolve your issue?

**Comment by danygutmann** [comment]
> Hey @danygutmann did you manage to resolve your issue?

Hey, 
uf i had personal problems. I try to reproduce & report until end of week, ok?
sorry for that...
BR Dany

**Comment by Jakar510** [comment]
I get this error on a Z Fold 5, Android 14.

**Comment by danygutmann** [comment]
with the testapp code it works also in my project...
A big sorry - it was my fault!

**Comment by danygutmann** [comment]
can be closed from my side @Jakar510 please reopen if you still have this issue.
